# Generated by Django 2.1.2 on 2018-10-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaka_grupe', models.CharField(max_length=10)),
                ('smer', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('lozinka', models.CharField(max_length=100, null=True)),
                ('uloga', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nastavnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200)),
                ('prezime', models.CharField(max_length=200)),
                ('titula', models.CharField(max_length=20, null=True)),
                ('zvanje', models.CharField(max_length=40, null=True)),
                ('nalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studserviceapp.Nalog')),
            ],
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('espb', models.IntegerField(null=True)),
                ('semestar_po_programu', models.IntegerField(null=True)),
                ('fond_predavanja', models.IntegerField(null=True)),
                ('fond_vezbe', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RasporedNastave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_unosa', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Semestar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(max_length=20)),
                ('skolska_godina_pocetak', models.IntegerField()),
                ('skolska_godina_kraj', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200)),
                ('prezime', models.CharField(max_length=200)),
                ('broj_indeksa', models.IntegerField()),
                ('godina_upisa', models.IntegerField()),
                ('smer', models.CharField(max_length=20)),
                ('grupa', models.ManyToManyField(to='studserviceapp.Grupa')),
                ('nalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studserviceapp.Nalog')),
            ],
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaka_ucionice', models.CharField(max_length=50)),
                ('pocetak', models.TimeField()),
                ('zavrsetak', models.TimeField()),
                ('dan', models.CharField(max_length=15)),
                ('tip_nastave', models.CharField(max_length=15)),
                ('grupe', models.ManyToManyField(to='studserviceapp.Grupa')),
                ('nastavnik', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Nastavnik')),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Predmet')),
                ('raspored', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studserviceapp.RasporedNastave')),
            ],
        ),
        migrations.AddField(
            model_name='rasporednastave',
            name='semestar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studserviceapp.Semestar'),
        ),
        migrations.AddField(
            model_name='nastavnik',
            name='predmet',
            field=models.ManyToManyField(to='studserviceapp.Predmet'),
        ),
        migrations.AddField(
            model_name='grupa',
            name='semestar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Semestar'),
        ),
    ]
