# Generated by Django 2.1.2 on 2018-11-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studserviceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IzborGrupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostvarenoESPB', models.IntegerField()),
                ('upisujeESPB', models.IntegerField()),
                ('broj_polozenih_ispita', models.IntegerField()),
                ('upisuje_semestar', models.IntegerField()),
                ('prvi_put_upisuje_semestar', models.BooleanField()),
                ('nacin_placanja', models.CharField(max_length=30)),
                ('upisan', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='IzbornaGrupa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaka_grupe', models.CharField(max_length=20)),
                ('oznaka_semestra', models.IntegerField()),
                ('kapacitet', models.IntegerField()),
                ('smer', models.CharField(max_length=20)),
                ('aktivna', models.BooleanField()),
                ('predmeti', models.ManyToManyField(to='studserviceapp.Predmet')),
                ('za_semestar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Semestar')),
            ],
        ),
        migrations.CreateModel(
            name='Konsultacije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesto', models.CharField(max_length=50)),
                ('vreme_od', models.TimeField()),
                ('vreme_do', models.TimeField()),
                ('dan', models.CharField(max_length=15)),
                ('nastavnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studserviceapp.Nastavnik')),
                ('predmet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studserviceapp.Predmet')),
            ],
        ),
        migrations.CreateModel(
            name='Obavestenje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_postavljanja', models.DateTimeField()),
                ('tekst', models.CharField(max_length=1000)),
                ('fajl', models.FileField(upload_to='')),
                ('postavio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Nalog')),
            ],
        ),
        migrations.CreateModel(
            name='RasporedPolaganja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispitni_rok', models.CharField(max_length=50, null=True)),
                ('kolokvijumska_nedelja', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TerminPolaganja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucionice', models.CharField(max_length=100)),
                ('pocetak', models.TimeField()),
                ('zavrsetak', models.TimeField()),
                ('datum', models.DateField()),
                ('nastavnik', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Nastavnik')),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Predmet')),
                ('raspored_polaganja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studserviceapp.RasporedPolaganja')),
            ],
        ),
        migrations.CreateModel(
            name='VazniDatumi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorija', models.CharField(max_length=200)),
                ('oznaka', models.CharField(max_length=200)),
                ('datum_od', models.DateField(null=True)),
                ('datum_do', models.DateField(null=True)),
                ('okvirno', models.CharField(max_length=200, null=True)),
                ('skolska_godina', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='rasporednastave',
            name='datum_unosa',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='izborgrupe',
            name='izabrana_grupa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studserviceapp.IzbornaGrupa'),
        ),
        migrations.AddField(
            model_name='izborgrupe',
            name='nepolozeni_predmeti',
            field=models.ManyToManyField(to='studserviceapp.Predmet'),
        ),
        migrations.AddField(
            model_name='izborgrupe',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Student'),
        ),
    ]
