# Generated by Django 2.1.2 on 2018-11-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studserviceapp', '0002_auto_20181111_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='izbornagrupa',
            name='broj_studenata',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
