# Generated by Django 2.1.2 on 2018-12-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studserviceapp', '0003_izbornagrupa_broj_studenata'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slika',
            field=models.ImageField(default=0, upload_to='djangouploads'),
            preserve_default=False,
        ),
    ]
