# Generated by Django 2.1.2 on 2018-12-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studserviceapp', '0004_student_slika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slika',
            field=models.FileField(upload_to='djangouploads'),
        ),
    ]
